import type { INodeType, INodeTypeDescription } from 'n8n-workflow';
import { NodeConnectionTypes } from 'n8n-workflow';
import {
	prepareBatchStatus,
	prepareSearch,
	prepareTask,
	prepareTaskIds,
	receiveBatchStatus,
	receiveCreditBalance,
	receiveSearch,
	receiveTask,
	receiveTaskIds,
} from './actions/routing';
import { OPENMART_API_ORIGIN } from './shared/request';

export class Openmart implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'Openmart',
		name: 'openmart',
		icon: { light: 'file:openmart.svg', dark: 'file:openmart.dark.svg' },
		group: ['input'],
		version: 1,
		subtitle: '={{$parameter["operation"] + ": " + $parameter["resource"]}}',
		description: 'Use the Openmart API',
		defaults: { name: 'Openmart' },
		usableAsTool: true,
		inputs: [NodeConnectionTypes.Main],
		outputs: [NodeConnectionTypes.Main],
		credentials: [{ name: 'openmartApi', required: true }],
		requestDefaults: {
			baseURL: OPENMART_API_ORIGIN,
			json: true,
			returnFullResponse: true,
			ignoreHttpStatusErrors: true,
		},
		properties: [
			{
				displayName: 'Resource',
				name: 'resource',
				type: 'options',
				noDataExpression: true,
				options: [
					{ name: 'Account', value: 'account' },
					{ name: 'Batch', value: 'batch' },
					{ name: 'Business', value: 'business' },
					{ name: 'Task', value: 'task' },
				],
				default: 'account',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['batch'] } },
				options: [
					{
						name: 'Get Status',
						value: 'getStatus',
						description: 'Get progress counts and readiness for an existing batch',
						action: 'Get batch status',
						routing: {
							request: { method: 'GET', url: '/api/v1/task/batch' },
							send: { preSend: [prepareBatchStatus] },
							output: { postReceive: [receiveBatchStatus] },
						},
					},
					{
						name: 'Get Task IDs',
						value: 'getTaskIds',
						description: 'Get task IDs from an existing batch',
						action: 'Get tasks from a batch',
						routing: {
							request: { method: 'GET', url: '/api/v1/task/batch' },
							send: { preSend: [prepareTaskIds] },
							output: { postReceive: [receiveTaskIds] },
						},
					},
				],
				default: 'getStatus',
			},
			{
				displayName: 'Batch ID',
				name: 'batchId',
				type: 'string',
				default: '',
				required: true,
				description: 'ID of the existing Openmart batch',
				displayOptions: {
					show: { resource: ['batch'], operation: ['getStatus', 'getTaskIds'] },
				},
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'string',
				default: '',
				description: 'Optional task status filter, for example COMPLETED',
				displayOptions: { show: { resource: ['batch'], operation: ['getTaskIds'] } },
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['account'] } },
				options: [
					{
						name: 'Get Credit Balance',
						value: 'getCreditBalance',
						description: 'Get the current credit balance and billing period',
						action: 'Get credit balance',
						routing: {
							request: { method: 'GET', url: '/api/v2/credit-balance' },
							output: { postReceive: [receiveCreditBalance] },
						},
					},
				],
				default: 'getCreditBalance',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['business'] } },
				options: [
					{
						name: 'Search',
						value: 'search',
						description: 'Find businesses matching a query',
						action: 'Search businesses',
						routing: {
							request: { method: 'POST', url: '/api/v1/search' },
							send: { preSend: [prepareSearch] },
							output: { postReceive: [receiveSearch] },
						},
					},
				],
				default: 'search',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['task'] } },
				options: [
					{
						name: 'Get',
						value: 'get',
						description: 'Get an existing task and its result data',
						action: 'Get a task',
						routing: {
							request: { method: 'GET', url: '/api/v1/task' },
							send: { preSend: [prepareTask] },
							output: { postReceive: [receiveTask] },
						},
					},
				],
				default: 'get',
			},
			{
				displayName: 'Task ID',
				name: 'taskId',
				type: 'string',
				default: '',
				required: true,
				description: 'ID of the existing Openmart task',
				displayOptions: { show: { resource: ['task'], operation: ['get'] } },
			},
			{
				displayName: 'Query',
				name: 'query',
				type: 'string',
				default: '',
				required: true,
				description: 'Natural-language description of businesses to find',
				displayOptions: { show: { resource: ['business'], operation: ['search'] } },
			},
			{
				displayName: 'Limit',
				name: 'resultLimit',
				type: 'number',
				default: 10,
				typeOptions: { minValue: 1, maxValue: 100 },
				description: 'Maximum number of businesses to return for this input item',
				displayOptions: { show: { resource: ['business'], operation: ['search'] } },
			},
			{
				displayName: 'Location',
				name: 'location',
				type: 'fixedCollection',
				default: {},
				placeholder: 'Add Location',
				typeOptions: { multipleValues: false },
				displayOptions: { show: { resource: ['business'], operation: ['search'] } },
				options: [
					{
						displayName: 'Location',
						name: 'locationValues',
						values: [
							{ displayName: 'Country', name: 'country', type: 'string', default: '' },
							{ displayName: 'State', name: 'state', type: 'string', default: '' },
							{ displayName: 'City', name: 'city', type: 'string', default: '' },
						],
					},
				],
			},
			{
				displayName: 'Filters',
				name: 'filters',
				type: 'collection',
				default: {},
				placeholder: 'Add Filter',
				displayOptions: { show: { resource: ['business'], operation: ['search'] } },
				options: [
					{
						displayName: 'Has Contact Info',
						name: 'has_contact_info',
						type: 'boolean',
						default: true,
					},
					{
						displayName: 'Has Valid Website',
						name: 'has_valid_website',
						type: 'boolean',
						default: true,
					},
					{ displayName: 'Has Website', name: 'has_website', type: 'boolean', default: true },
					{
						displayName: 'Minimum Locations',
						name: 'min_locations',
						type: 'number',
						default: 1,
						typeOptions: { minValue: 1 },
					},
				],
			},
		],
	};
}
