import type { INodeType, INodeTypeDescription } from 'n8n-workflow';
import { NodeConnectionTypes } from 'n8n-workflow';
import {
	prepareBatchStatus,
	prepareCompanyEmail,
	prepareCompanyEnrich,
	prepareCompanySearch,
	prepareKnownPeople,
	preparePeopleSearch,
	prepareSearch,
	prepareTask,
	prepareTaskIds,
	receiveBatchStatus,
	receiveCompanyEmail,
	receiveCompanyEnrich,
	receiveCompanySearch,
	receiveKnownPeople,
	receiveCreditBalance,
	receiveSearch,
	receivePeopleSearch,
	receiveTask,
	receiveTaskIds,
} from './actions/routing';
import { OPENMART_API_ORIGIN } from './shared/request';

export class Openmart implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'Openmart',
		name: 'openmart',
		icon: { light: 'file:openmart.png', dark: 'file:openmart.dark.png' },
		group: ['input'],
		version: 1,
		subtitle: '={{$parameter["operation"] + ": " + $parameter["resource"]}}',
		description: 'Use the Openmart API',
		defaults: { name: 'Openmart' },
		usableAsTool: true,
		inputs: [NodeConnectionTypes.Main],
		outputs: [NodeConnectionTypes.Main],
		credentials: [{ name: 'openmartApi', required: true }],
		requestDefaults: {
			baseURL: OPENMART_API_ORIGIN,
			json: true,
			returnFullResponse: true,
			ignoreHttpStatusErrors: true,
		},
		properties: [
			{
				displayName: 'Resource',
				name: 'resource',
				type: 'options',
				noDataExpression: true,
				options: [
					{ name: 'Account', value: 'account' },
					{ name: 'Batch', value: 'batch' },
					{ name: 'Business', value: 'business' },
					{ name: 'Company', value: 'company' },
					{ name: 'Person', value: 'person' },
					{ name: 'Task', value: 'task' },
				],
				default: 'account',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['batch'] } },
				options: [
					{
						name: 'Get Status',
						value: 'getStatus',
						description: 'Get progress counts and readiness for an existing batch',
						action: 'Get batch status',
						routing: {
							request: { method: 'GET', url: '/api/v1/task/batch' },
							send: { preSend: [prepareBatchStatus] },
							output: { postReceive: [receiveBatchStatus] },
						},
					},
					{
						name: 'Get Task IDs',
						value: 'getTaskIds',
						description: 'Get task IDs from an existing batch',
						action: 'Get tasks from a batch',
						routing: {
							request: { method: 'GET', url: '/api/v1/task/batch' },
							send: { preSend: [prepareTaskIds] },
							output: { postReceive: [receiveTaskIds] },
						},
					},
				],
				default: 'getStatus',
			},
			{
				displayName: 'Batch ID',
				name: 'batchId',
				type: 'string',
				default: '',
				required: true,
				description: 'ID of the existing Openmart batch',
				displayOptions: {
					show: { resource: ['batch'], operation: ['getStatus', 'getTaskIds'] },
				},
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'string',
				default: '',
				description: 'Optional task status filter, for example COMPLETED',
				displayOptions: { show: { resource: ['batch'], operation: ['getTaskIds'] } },
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['account'] } },
				options: [
					{
						name: 'Get Credit Balance',
						value: 'getCreditBalance',
						description: 'Get the current credit balance and billing period',
						action: 'Get credit balance',
						routing: {
							request: { method: 'GET', url: '/api/v2/credit-balance' },
							output: { postReceive: [receiveCreditBalance] },
						},
					},
				],
				default: 'getCreditBalance',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['business'] } },
				options: [
					{
						name: 'Search',
						value: 'search',
						description: 'Find businesses matching a query',
						action: 'Search businesses',
						routing: {
							request: { method: 'POST', url: '/api/v1/search' },
							send: { preSend: [prepareSearch] },
							output: { postReceive: [receiveSearch] },
						},
					},
				],
				default: 'search',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['task'] } },
				options: [
					{
						name: 'Get',
						value: 'get',
						description: 'Get an existing task and its result data',
						action: 'Get a task',
						routing: {
							request: { method: 'GET', url: '/api/v1/task' },
							send: { preSend: [prepareTask] },
							output: { postReceive: [receiveTask] },
						},
					},
				],
				default: 'get',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['company'] } },
				options: [
					{
						name: 'Find Emails',
						value: 'findEmails',
						description: 'Create paid background work to find generic shared inbox addresses',
						action: 'Find company emails',
						routing: {
							request: {
								method: 'POST',
								url: '/api/v1/task/batch/lookup_business_email',
								timeout: 90_000,
							},
							send: { preSend: [prepareCompanyEmail] },
							output: { postReceive: [receiveCompanyEmail] },
						},
					},
					{
						name: 'Search',
						value: 'search',
						description:
							'Return one row per brand; use Business Search for local or store-level leads',
						action: 'Search companies',
						routing: {
							request: { method: 'POST', url: '/api/v2/brands/search' },
							send: { preSend: [prepareCompanySearch] },
							output: { postReceive: [receiveCompanySearch] },
						},
					},
					{
						name: 'Enrich',
						value: 'enrich',
						description:
							'Match existing Openmart records from a website or social media link; does not crawl arbitrary sites',
						action: 'Enrich a company',
						routing: {
							request: { method: 'POST', url: '/api/v1/enrich_company' },
							send: { preSend: [prepareCompanyEnrich] },
							output: { postReceive: [receiveCompanyEnrich] },
						},
					},
				],
				default: 'search',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['person'] } },
				options: [
					{
						name: 'Find Decision Makers',
						value: 'findDecisionMakers',
						description: 'Create paid background work to find decision makers',
						action: 'Find decision makers',
						routing: {
							request: {
								method: 'POST',
								url: '/api/v1/task/batch/find_people',
								timeout: 90_000,
							},
							send: { preSend: [preparePeopleSearch] },
							output: { postReceive: [receivePeopleSearch] },
						},
					},
					{
						name: 'Enrich Known Person',
						value: 'enrich',
						description: 'Create paid background work to enrich known people',
						action: 'Enrich known people',
						routing: {
							request: { method: 'POST', url: '/api/v1/task/batch/lookup_people', timeout: 90_000 },
							send: { preSend: [prepareKnownPeople] },
							output: { postReceive: [receiveKnownPeople] },
						},
					},
				],
				default: 'findDecisionMakers',
			},
			{
				displayName:
					'Each input item creates one potentially charged background task. Retries or manual reruns can duplicate charged work. Retrieve results with Batch Get Status → Batch Get Task IDs → Task Get.',
				name: 'paidCreationNotice',
				type: 'notice',
				default: '',
				displayOptions: {
					show: { resource: ['company'], operation: ['findEmails'] },
				},
			},
			{
				displayName:
					'Each input item creates one potentially charged background task. Retries or manual reruns can duplicate charged work. Retrieve results with Batch Get Status → Batch Get Task IDs → Task Get.',
				name: 'paidPersonNotice',
				type: 'notice',
				default: '',
				displayOptions: {
					show: { resource: ['person'], operation: ['findDecisionMakers', 'enrich'] },
				},
			},
			{
				displayName: 'Domain',
				name: 'domain',
				type: 'string',
				default: '',
				required: true,
				description: 'Company hostname or HTTP/HTTPS URL; normalized to a hostname',
				displayOptions: {
					show: { resource: ['company'], operation: ['findEmails'] },
				},
			},
			{
				displayName: 'Domain',
				name: 'domain',
				type: 'string',
				default: '',
				required: true,
				description: 'Company hostname or HTTP/HTTPS URL; normalized to a hostname',
				displayOptions: {
					show: { resource: ['person'], operation: ['findDecisionMakers', 'enrich'] },
				},
			},
			{
				displayName: 'Company Name',
				name: 'companyName',
				type: 'string',
				default: '',
				required: true,
				displayOptions: { show: { resource: ['company'], operation: ['findEmails'] } },
			},
			{
				displayName: 'Company Name',
				name: 'companyName',
				type: 'string',
				default: '',
				description: 'Optional company name to help narrow the people search',
				displayOptions: {
					show: { resource: ['person'], operation: ['findDecisionMakers', 'enrich'] },
				},
			},
			{
				displayName: 'Title',
				name: 'title',
				type: 'string',
				default: 'Owner or decision maker',
				required: true,
				displayOptions: { show: { resource: ['person'], operation: ['findDecisionMakers'] } },
			},
			{
				displayName: 'Max Contacts',
				name: 'maxK',
				type: 'number',
				default: 1,
				required: true,
				typeOptions: { minValue: 1, maxValue: 8 },
				displayOptions: { show: { resource: ['person'], operation: ['findDecisionMakers'] } },
			},
			{
				displayName: 'Contact Information',
				name: 'infoAccess',
				type: 'multiOptions',
				default: ['EMAIL'],
				required: true,
				options: [
					{ name: 'Email', value: 'EMAIL' },
					{ name: 'Phone', value: 'PHONE' },
				],
				description: 'Contact information types to request',
				displayOptions: {
					show: { resource: ['person'], operation: ['findDecisionMakers', 'enrich'] },
				},
			},
			{
				displayName: 'City',
				name: 'city',
				type: 'string',
				default: '',
				displayOptions: {
					show: { resource: ['company'], operation: ['findEmails'] },
				},
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
				placeholder: 'e.g. CA',
				description: 'For US locations, use the two-letter state code (for example, CA)',
				displayOptions: {
					show: { resource: ['company'], operation: ['findEmails'] },
				},
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				default: '',
				displayOptions: {
					show: { resource: ['company'], operation: ['findEmails'] },
				},
			},
			{
				displayName: 'Tracking ID',
				name: 'trackingId',
				type: 'string',
				default: '',
				description: 'Optional caller-defined correlation ID',
				displayOptions: {
					show: { resource: ['company'], operation: ['findEmails'] },
				},
			},
			...['city', 'state', 'country', 'trackingId'].map((name) => ({
				displayName: (
					{ city: 'City', state: 'State', country: 'Country', trackingId: 'Tracking ID' } as const
				)[name]!,
				name,
				type: 'string' as const,
				default: '',
				...(name === 'state'
					? {
							placeholder: 'e.g. CA',
							description: 'For US locations, use the two-letter state code (for example, CA)',
						}
					: {}),
				displayOptions: {
					show: { resource: ['person'], operation: ['findDecisionMakers', 'enrich'] },
				},
			})),
			{
				displayName: 'People',
				name: 'people',
				type: 'fixedCollection',
				default: {},
				required: true,
				placeholder: 'Add Person',
				typeOptions: { multipleValues: true },
				displayOptions: { show: { resource: ['person'], operation: ['enrich'] } },
				options: [
					{
						displayName: 'Person',
						name: 'person',
						values: [
							{
								displayName: 'First Name',
								name: 'firstName',
								type: 'string',
								default: '',
								required: true,
							},
							{
								displayName: 'Last Name',
								name: 'lastName',
								type: 'string',
								default: '',
								required: true,
							},
							{ displayName: 'LinkedIn URL', name: 'linkedinUrl', type: 'string', default: '' },
						],
					},
				],
			},
			{
				displayName: 'Search Term',
				name: 'companySearchTerm',
				type: 'string',
				default: '',
				description: 'Brand-level relevance term',
				displayOptions: { show: { resource: ['company'], operation: ['search'] } },
			},
			{
				displayName: 'Location',
				name: 'companySearchLocation',
				type: 'fixedCollection',
				default: {},
				placeholder: 'Add Location',
				typeOptions: { multipleValues: false },
				displayOptions: { show: { resource: ['company'], operation: ['search'] } },
				options: [
					{
						displayName: 'Location',
						name: 'locationValues',
						values: [
							{ displayName: 'Country', name: 'country', type: 'string', default: 'US' },
							{
								displayName: 'State',
								name: 'state',
								type: 'string',
								default: '',
								placeholder: 'e.g. CA',
								description: 'For US locations, use the two-letter state code (for example, CA)',
							},
							{ displayName: 'City', name: 'city', type: 'string', default: '' },
						],
					},
				],
			},
			{
				displayName: 'Ownership Type',
				name: 'ownershipType',
				type: 'multiOptions',
				default: [],
				options: [
					{ name: 'Chain', value: 'CHAIN' },
					{ name: 'Family', value: 'FAMILY' },
					{ name: 'Franchise', value: 'FRANCHISE' },
					{ name: 'Independent', value: 'INDEPENDENT' },
				],
				displayOptions: { show: { resource: ['company'], operation: ['search'] } },
			},
			{
				displayName: 'Store Count',
				name: 'storeCount',
				type: 'collection',
				default: {},
				placeholder: 'Add Store Count Filter',
				options: [
					{
						displayName: 'Maximum Store Count',
						name: 'maximumStores',
						type: 'number',
						default: 0,
						typeOptions: { minValue: 0 },
					},
					{
						displayName: 'Minimum Store Count',
						name: 'minimumStores',
						type: 'number',
						default: 0,
						typeOptions: { minValue: 0 },
					},
				],
				displayOptions: { show: { resource: ['company'], operation: ['search'] } },
			},
			...['hasStaffInfo', 'hasBusinessEmail', 'hasBusinessPhone'].map((name, index) => ({
				displayName: ['Has Staff Info', 'Has Business Email', 'Has Business Phone'][index]!,
				name,
				type: 'options' as const,
				default: '',
				options: [
					{ name: 'Any', value: '' },
					{ name: 'Yes', value: true },
					{ name: 'No', value: false },
				],
				displayOptions: { show: { resource: ['company'], operation: ['search'] } },
			})),
			{
				displayName: 'Limit',
				name: 'companySearchLimit',
				type: 'number',
				default: 10,
				typeOptions: { minValue: 1, maxValue: 100 },
				description: 'Maximum brand-level companies to return from the first page',
				displayOptions: { show: { resource: ['company'], operation: ['search'] } },
			},
			{
				displayName: 'Website',
				name: 'website',
				type: 'string',
				default: '',
				displayOptions: { show: { resource: ['company'], operation: ['enrich'] } },
			},
			{
				displayName: 'Social Media Link',
				name: 'socialMediaLink',
				type: 'string',
				default: '',
				displayOptions: { show: { resource: ['company'], operation: ['enrich'] } },
			},
			{
				displayName: 'Location',
				name: 'companyEnrichLocation',
				type: 'fixedCollection',
				default: {},
				placeholder: 'Add Location',
				typeOptions: { multipleValues: false },
				displayOptions: { show: { resource: ['company'], operation: ['enrich'] } },
				options: [
					{
						displayName: 'Location',
						name: 'locationValues',
						values: [
							{ displayName: 'Country', name: 'country', type: 'string', default: '' },
							{
								displayName: 'State',
								name: 'state',
								type: 'string',
								default: '',
								placeholder: 'e.g. CA',
								description: 'For US locations, use the two-letter state code (for example, CA)',
							},
							{ displayName: 'City', name: 'city', type: 'string', default: '' },
						],
					},
				],
			},
			{
				displayName: 'Limit',
				name: 'companyEnrichLimit',
				type: 'number',
				default: 10,
				typeOptions: { minValue: 1, maxValue: 50 },
				displayOptions: { show: { resource: ['company'], operation: ['enrich'] } },
			},
			{
				displayName: 'Task ID',
				name: 'taskId',
				type: 'string',
				default: '',
				required: true,
				description: 'ID of the existing Openmart task',
				displayOptions: { show: { resource: ['task'], operation: ['get'] } },
			},
			{
				displayName: 'Query',
				name: 'query',
				type: 'string',
				default: '',
				required: true,
				description: 'Natural-language description of businesses to find',
				displayOptions: { show: { resource: ['business'], operation: ['search'] } },
			},
			{
				displayName: 'Limit',
				name: 'resultLimit',
				type: 'number',
				default: 10,
				typeOptions: { minValue: 1, maxValue: 100 },
				description: 'Maximum number of businesses to return for this input item',
				displayOptions: { show: { resource: ['business'], operation: ['search'] } },
			},
			{
				displayName: 'Location',
				name: 'location',
				type: 'fixedCollection',
				default: {},
				placeholder: 'Add Location',
				typeOptions: { multipleValues: false },
				displayOptions: { show: { resource: ['business'], operation: ['search'] } },
				options: [
					{
						displayName: 'Location',
						name: 'locationValues',
						values: [
							{ displayName: 'Country', name: 'country', type: 'string', default: '' },
							{
								displayName: 'State',
								name: 'state',
								type: 'string',
								default: '',
								placeholder: 'e.g. CA',
								description: 'For US locations, use the two-letter state code (for example, CA)',
							},
							{ displayName: 'City', name: 'city', type: 'string', default: '' },
						],
					},
				],
			},
			{
				displayName: 'Filters',
				name: 'filters',
				type: 'collection',
				default: {},
				placeholder: 'Add Filter',
				displayOptions: { show: { resource: ['business'], operation: ['search'] } },
				options: [
					{
						displayName: 'Has Contact Info',
						name: 'has_contact_info',
						type: 'boolean',
						default: true,
					},
					{
						displayName: 'Has Valid Website',
						name: 'has_valid_website',
						type: 'boolean',
						default: true,
					},
					{ displayName: 'Has Website', name: 'has_website', type: 'boolean', default: true },
					{
						displayName: 'Minimum Locations',
						name: 'min_locations',
						type: 'number',
						default: 1,
						typeOptions: { minValue: 1 },
					},
				],
			},
		],
	};
}
